apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gop.fullname" . }}
  labels:
    {{- include "gop.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ .Values.config | toYaml | indent 4 }}

